name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

  workflow_dispatch:

jobs:
  test:
    name: build and test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: backend/yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Generate prisma graphql types
        run: yarn prisma:generate

      - name: Lint the repository
        run: yarn lint

      - name: Build the backend
        run: yarn build

      - name: Run all integration/e2e tests
        run: yarn test --coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3


